//Liquid

//double molesOfPairs{0};
//int numberOfPairs{0};
//int numberOfQuadruplets{0};

/*
    char quadruplet_Li_Li_F_F[25] = "Li-Li-F-F";
    double moleFraction_Li_Li_F_F{0};

    char quadruplet_U4_U4_F_F[25] = "U4-U4-F-F";
    double moleFraction_U4_U4_F_F{0};

    char quadruplet_U3_U3_F_F[25] = "U3-U3-F-F";
    double moleFraction_U3_U3_F_F{0};
    
    char quadruplet_U4_U3_F_F[25] = "U4-U3-F-F";
    double moleFraction_U4_U3_F_F{0};
*/

/*
char phaseName_K_liquid[25] = "K_liquid";
double molesPhase_K_liquid{0};

char phaseName_Na_liquid[25] = "Na_liquid";
double molesPhase_Na_liquid{0};

char phaseName_Li_liquid[25] = "Li_liquid";
double molesPhase_Li_liquid{0};

char phaseName_Cs_liquid[25] = "Cs_liquid";
double molesPhase_Cs_liquid{0};
*/

/*
//Solid
char phaseName_solid1[25] = "solid1"; //This phase can be huge
double molesPhase_solid1{0};

char phaseName_Liq1_NaF[25] = "LiF-NaF";
double molesPhase_Liq1_NaF{0};

char phaseName_NaF_KF[25] = "NaF-KF";
double molesPhase_NaF_KF{0};

    char speciesName_Liq1[8] = "LiF";
    double moleFraction_Liq1{0};
    char speciesName_KF[8] = "KF";
    double moleFraction_KF{0};
    char speciesName_CsF[8] = "CsF";
    double moleFraction_CsF{0};
    char speciesName_NaF[8] = "NaF";
    double moleFraction_NaF{0};
    char speciesName_Liq4[8] = "Liq4";
    double moleFraction_Liq4{0};
    char speciesName_Liq5[8] = "Liq5";
    double moleFraction_Liq5{0};
    char speciesName_F2[8] = "F2";
    double moleFraction_F2{0};

char phaseName_LaK3F6_solid[25] = "LaK3F6_solid";
double molesPhase_LaK3F6{0};

char phaseName_CeF3_solid[25] = "CeF3_solid";
double molesPhase_CeF3_solid{0};

char phaseName_CsF2Li_solids[25] = "CsF2Li_solids";
double molesPhase_CsF2Li_solids{0};

char phaseName_FLi_solids[25] = "FLi_solids";
double molesPhase_FLi_solids{0};

char phaseName_CsF_solids[25] = "CsF_solids";
double molesPhase_CsF_solids{0};


char phaseName_Na2ThUF6 [25] = "Na2(Th,U)F6 ";     // ThNa2F6   UNa2F6
double molesPhase_Na2ThUF6{0};

    char speciesName_ThNa2F6[16] = "ThNa2F6";
    double moleFraction_ThNa2F6{0};

    char speciesName_UNa2F6[16] = "UNa2F6";
    double moleFraction_UNa2F6{0};


char phaseName_LiNa7Th6F[25] = "(Li,Na)7Th6F";     // Th6Na7F31   Th6F31Li7
double molesPhase_LiNa7Th6F{0};

    char speciesName_Th6Na7F31[16] = "Th6Na7F31";
    double moleFraction_Th6Na7F31{0};

    char speciesName_Th6F31Li7[16] = "Th6F31Li7";
    double moleFraction_Th6F31Li7{0};


char phaseName_Li7ThU6F3[25] = "Li7(Th,U)6F3";
double molesPhase_Li7ThU6F3{0};

    char speciesName_ThF5Li[16] = "ThF5Li";
    double moleFraction_ThF5Li{0};

    char speciesName_U6F31Li7[16] = "U6F31Li7";
    double moleFraction_U6F31Li7{0};
*/